### ISSUE TITLE
Failed to build on MacOS Monterey

### ISSUE THREAD

**Issue by Jash-Shah** [Jash-Shah/pyGnuastro#4]
The current dev version on pyGnuastro uploaded on [TestPyPI](https://test.pypi.org/project/pygnuastro/) failed to install on a `MacOS Monterey system with Python 3.9.13`.

The commands used to install the dev version of the package were(a virtual env is created to test a clean install):
```
python3 -m venv pygnuastro
source pygnuastro/bin/activate
# extra-index-url has to be supplied to avoid pip installing the dependencies from TestPyPI instead of PyPI
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/  pygnuastro
```

The error message received was due to pip defaulting to source dist(`.tar.gz`) instead of the macOS wheels. The error received was similar to:
```
Processing ./pygnuastro-0.0.1.dev2.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "/home/jash-ubuntu/Desktop/Coding_Trash/GSoC/GNUAstro/pygnuastro/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/jash-ubuntu/Desktop/Coding_Trash/GSoC/GNUAstro/pygnuastro/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/jash-ubuntu/Desktop/Coding_Trash/GSoC/GNUAstro/pygnuastro/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-568d5uv6/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-568d5uv6/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-568d5uv6/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 3, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by affan00733** [comment]
Hi ,
I am a working professional and willing to participate in GSOC 2023 so want to solve this issue

**Comment by Jash-Shah** [comment]
Hey @affan00733, for GSoC, I would recommend you to focus more on the Gnuastro side of things for now, instead of pyGnuastro. Specifically starting with the [GSoC 2023 Checklist](https://savannah.gnu.org/support/?110827) and also joining the [Gnuastro Element Room](https://matrix.to/#/#gnuastro:openastronomy.org) for further discussing the project with the Mentors!
